/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, copyDefault, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && (copyDefault || key !== "default"))
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toCommonJS = /* @__PURE__ */ ((cache) => {
  return (module2, temp) => {
    return cache && cache.get(module2) || (temp = __reExport(__markAsModule({}), module2, 1), cache && cache.set(module2, temp), temp);
  };
})(typeof WeakMap !== "undefined" ? /* @__PURE__ */ new WeakMap() : 0);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ForceRefreshPlugin
});
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  showNotice: true,
  recursive: true
};
var ForceRefreshPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("refresh-ccw", "Force Refresh", (evt) => {
      this.refreshFilesystem();
    });
    this.addCommand({
      id: "force-refresh-filesystem",
      name: "Force Refresh",
      callback: () => {
        this.refreshFilesystem();
      }
    });
    this.addCommand({
      id: "force-reload-app",
      name: "Force Reload App (Nuclear)",
      callback: () => {
        this.app.commands.executeCommandById("app:reload");
      }
    });
    this.addSettingTab(new ForceRefreshSettingTab(this.app, this));
  }
  async refreshFilesystem() {
    console.log("Force Refresh: Starting filesystem refresh...");
    const { vault, workspace } = this.app;
    try {
      console.log("Force Refresh: Scanning filesystem for external modifications...");
      const filesToNotify = [];
      const scanRecursive = async (path) => {
        const result = await vault.adapter.list(path);
        for (const filePath of result.files) {
          filesToNotify.push(filePath);
        }
        for (const folderPath of result.folders) {
          await scanRecursive(folderPath);
        }
      };
      await scanRecursive("");
      const diskFileSet = new Set(filesToNotify);
      const vaultFileSet = new Set(vault.getFiles().map((f) => f.path));
      const newFiles = filesToNotify.filter((p) => !vaultFileSet.has(p));
      const knownFiles = filesToNotify.filter((p) => vaultFileSet.has(p));
      console.log(`Force Refresh: Found ${diskFileSet.size} files on disk. New to Obsidian: ${newFiles.length}, Already known: ${knownFiles.length}.`);
      const adapter = vault.adapter;
      if (newFiles.length > 0) {
        if (typeof adapter.onChange === "function") {
          console.log("Force Refresh: Notifying vault of new files via adapter.onChange...");
          for (const path of newFiles) {
            await adapter.onChange("created", path);
          }
        } else if (typeof vault.reconcileFile === "function") {
          console.log("Force Refresh: Notifying vault of new files via reconcileFile...");
          for (const path of newFiles) {
            await vault.reconcileFile(path, "");
          }
        } else {
          console.warn("Force Refresh: No method found to register new files. New files may not appear until Obsidian is restarted.");
        }
      }
      for (const path of knownFiles) {
        const abstractFile = vault.getAbstractFileByPath(path);
        if (abstractFile) {
          vault.trigger("modify", abstractFile);
        }
      }
      console.log("Force Refresh: Reconciliation step complete.");
      const fileExplorerLeaves = workspace.getLeavesOfType("file-explorer");
      for (const leaf of fileExplorerLeaves) {
        if (leaf.view) {
          const view = leaf.view;
          if (typeof view.requestPopulate === "function") {
            view.requestPopulate();
          } else if (typeof view.reload === "function") {
            view.reload();
          }
        }
      }
      workspace.trigger("layout-change");
      if (this.settings.showNotice) {
        new import_obsidian.Notice(`Filesystem refresh complete. Found ${diskFileSet.size} files (${newFiles.length} new).`);
      }
      console.log("Force Refresh: Filesystem refresh complete.");
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      console.error("Force Refresh: Error during filesystem refresh:", error);
      new import_obsidian.Notice(`Error: ${msg}`);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var ForceRefreshSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Settings for Force Refresh" });
    new import_obsidian.Setting(containerEl).setName("Show Notice").setDesc("Show a notification in the UI when the refresh is complete.").addToggle((toggle) => toggle.setValue(this.plugin.settings.showNotice).onChange(async (value) => {
      this.plugin.settings.showNotice = value;
      await this.plugin.saveSettings();
    }));
  }
};
module.exports = __toCommonJS(main_exports);
